trainer:
  save_dir: experiments/classification/siim/SHARP_100pct
  model_name: SHARP
  seed: 42
  epochs: 50
  amp: true
  gpus: [0]
  num_workers: 4
  eval_only: false
  batch_size: 64
  accumulate_grad_batches: 1
  num_sanity_val_steps: 0
  early_stop: 10
  encoder_lr_scale: 0.1
  optimizer: SGD
  optim_params:
    lr: 1e-2
    momentum: 0.9
    weight_decay: 0.0
  scheduler_params:
    patience: 1
    factor: 0.5
    mode: min

data:
  data_pct: 100%
  dataset: SIIM
  exp_name: SHARP_100pct

model:
  cnn:
    ckpt: false
    pretrained: D:/experiments/exp3_full_sharp/p3_best_timm.pt
    type: vit_base_patch16_224
    finetune_method: linear_prob
